import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";
import App from "./App.jsx";
import { nanoid } from "nanoid";

const DATA = [
  { id: `todo-${nanoid()}`, location: "moon/image_007.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_010.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_030.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_036.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_018.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_062.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_027.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_024.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_028.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_017.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_001.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_040.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_026.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_035.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_056.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_033.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_012.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_060.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_011.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_053.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_013.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_049.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_045.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_052.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_016.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_048.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_044.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_039.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_037.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_014.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_005.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_004.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_006.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_022.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_061.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_003.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_041.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_050.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_020.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_031.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_047.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_059.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_019.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_034.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_046.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_009.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_038.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_042.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_021.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_029.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_015.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_063.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_057.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_032.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_051.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_058.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_043.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_064.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_055.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_023.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_008.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_002.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_054.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "moon/image_025.jpg", type: 0 },
  { id: `todo-${nanoid()}`, location: "stars/Alcor_and_Mizar.png", type: 1 },
  { id: `todo-${nanoid()}`, location: "stars/IMG_3058.PNG", type: 1 },
  { id: `todo-${nanoid()}`, location: "stars/Altair.png", type: 1 },
  { id: `todo-${nanoid()}`, location: "stars/IMG_3409.jpg", type: 1 },
  { id: `todo-${nanoid()}`, location: "stars/Sirius(03).jpg", type: 1 },
  { id: `todo-${nanoid()}`, location: "stars/Sirius(02).jpg", type: 1 },
  { id: `todo-${nanoid()}`, location: "stars/Sirius(01).jpg", type: 1 },
  { id: `todo-${nanoid()}`, location: "deepsky/IMG_3453.PNG", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/Ring_Nebulae(01).png", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/Ring_Nebulae(02).png", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/IMG_3451.jpg", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/M110.png", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/IMG_3448.jpg", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/IMG_2925.PNG", type: 2 },
  {
    id: `todo-${nanoid()}`,
    location: "deepsky/Tsuchinshan-ATLAS.jpg",
    type: 2,
  },
  { id: `todo-${nanoid()}`, location: "deepsky/IMG_3452.jpg", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/M13.png", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/Andromede.png", type: 2 },
  { id: `todo-${nanoid()}`, location: "deepsky/IMG_3447.jpg", type: 2 },
  { id: `todo-${nanoid()}`, location: "openfield/IMAGE_153.png", type: 3 },
  { id: `todo-${nanoid()}`, location: "openfield/processed.png", type: 3 },
  {
    id: `todo-${nanoid()}`,
    location: "openfield/962351E9-46EC-453A-9E8F-AF80298616E6.JPG",
    type: 3,
  },
  { id: `todo-${nanoid()}`, location: "openfield/processed2.png", type: 3 },
  { id: `todo-${nanoid()}`, location: "planets/Saturn(01).png", type: 4 },
  { id: `todo-${nanoid()}`, location: "planets/Saturn(02).png", type: 4 },
  { id: `todo-${nanoid()}`, location: "planets/Jupiter.jpg", type: 4 },
];

const TYPES = ["Moon", "Stars", "Deep Sky", "Open Field", "Planetary"];

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App images={DATA} />
  </StrictMode>
);
